### ISSUE TITLE
Renderer should check block before getting properties

### ISSUE THREAD

**Issue by embeddedt** [Alexandra-Myers/PandorasBox#2]
If the game does not remesh a chunk after the Pandora's Box block is removed [here](https://github.com/Alexandra-Myers/PandorasBox/blob/6bcac95dc1000b45d39595f0398e492114c5848a/src/main/java/ivorius/pandorasbox/block/PandorasBoxBlock.java#L74) (this seems to only occur reliably with Embeddium, but a code analysis suggests it can occur in vanilla too), the block entity remains in the list to render on the next frame. When that happens, the following function will crash as it tries to retrieve a direction property from an air block.

https://github.com/Alexandra-Myers/PandorasBox/blob/6bcac95dc1000b45d39595f0398e492114c5848a/src/main/java/ivorius/pandorasbox/block/PandorasBoxBlockEntity.java#L46

To fix this, a check should be added that checks whether `state.getBlock() instanceof PandorasBoxBlock`, and if that is not satisfied, a default rotation should be returned. Other vanilla block entities (e.g. the shulker box in its block entity renderer) use a similar check.

I've worked around this in Embeddium by [refusing to render removed BEs](https://github.com/embeddedt/embeddium/commit/088da77632385585bf7d4ff2c759a279a259691f), but vanilla doesn't require that so I think this will still crash in vanilla under the right conditions.

**Comment by Alexandra-Myers** [comment]
fixed in next update
